### ISSUE TITLE
bundle tray icon image into application

### ISSUE THREAD

**Issue by nikhilsaraf** [asticode/go-astilectron-bundler#57]
I'm trying to bundle the image for the tray icon with my deployment, but it fails to copy the tray icon image into the bundled file (MacOS).

This gives an error when trying to start the app because the tray icon is missing in the packaged binary.

I'm certain this should be possible but just couldn't get it to work. I even see the byte-version of the image in the bind_*.go files.

**Comment by nikhilsaraf** [comment]
^@asticode

**Comment by asticode** [comment]
are you using the [bootstrap](https://github.com/asticode/go-astilectron-bootstrap) ?

**Comment by nikhilsaraf** [comment]
Yes

**Comment by khuderm** [comment]
at least the auto generated plst file is ignoring icon paths 
```
<key>CFBundleIconFile</key>
		<string>`+b.appName+filepath.Ext(b.pathIconDarwin)+`</string>
```

**Comment by nikhilsaraf** [comment]
To get around this issue I'm writing out the icon file (png) to disk from the _bind_ file that is generated by the bundler ([link to source code](https://github.com/stellar/kelp/blob/b725cbaf9c67e8d3b9aea29316c5ec22d168c81e/cmd/server.go#L208)). Then I pass the path of that generated icon file to the TrayOptions ([link to source code](https://github.com/stellar/kelp/blob/b725cbaf9c67e8d3b9aea29316c5ec22d168c81e/cmd/server.go#L283)).

If there's a better way to do this such as specifying which files in the `resources` directory we also want included in the final package that would be very helpful

**Comment by asticode** [comment]
@khuderm This section of the plst file is for the App icon, not the Tray icon. And no need to take the path into account since the icon has been [moved](https://github.com/asticode/go-astilectron-bundler/blob/master/bundler.go#L646) by the bundler.

@nikhilsaraf  The path you provide for the Tray is relative to the app directory. As your tray icon must be in the `resources` folder, the path you set in the bootstrap `Options` should be `resources/path/to/icon.png` so in your case `resources/kelp-icon@1-8x.png`. Does that work better ?

**Comment by nikhilsaraf** [comment]
@asticode that didn't work for me and I got the same error. The icon was not copied over.

**Comment by asticode** [comment]
Does the app icon gets copied ? `resources/kelp-icon@2x.png` in your case ?

**Comment by nikhilsaraf** [comment]
@asticode yes that gets copied, probably because it’s specified in the bundled.json file ([source code](https://github.com/stellar/kelp/blob/b725cbaf9c67e8d3b9aea29316c5ec22d168c81e/bundler.json))
