### ISSUE TITLE
How to bundle extrafiles?

### ISSUE THREAD

**Issue by tpoxa** [asticode/go-astilectron-bundler#77]
Thanks for the great project you did. I think I need to bundle extra binaries into my project. Like git client. What is the proper way to do it?

**Comment by asticode** [comment]
@tpoxa you can use [this attribute](https://github.com/asticode/go-astilectron-bundler/blob/master/bundler.go#L74) to copy all your extra binaries to the resources dir so that they get bind to your final binary.

Let's imagine you want to bind 2 extra binaries located at `/path/to/binary/1` and `/path/to/binary/2`, you'd have to add the following JSON to the `resources_adapters` attribute :

```json
[
  {
    "args": ["/path/to/binary/1", "/path/to/binary/2", "."],
    "name": "cp"
  }
]
```

As this command will be executed in the resources dir about to be bind, your binaries will get bind to your final binary.

Let me know if you're experiencing any problem.

**Comment by tpoxa** [comment]
Thanks!
